language: ruby
cache: bundler
sudo: false

before_script: &before_script
  - psql -c 'create database travis_ci_test;' -U postgres
  - FIG_RAKE=off RACK_ENV=test bundle exec rake configure:travis db:create db:migrate

jruby_before_script: &jruby_before_script
  - bundle exec jbundle install
  - psql -c 'create database travis_ci_test;' -U postgres
  - FIG_RAKE=off RACK_ENV=test bundle exec rake configure:travis db:create db:migrate

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.1.5
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 2.2.0
  include:
    - rvm: 2.1.2
    - rvm: jruby-1.7.17
      env: JRUBY_OPTS=--2.0 FIG_RAKE=off
      jdk: openjdk7
      before_script: *jruby_before_script
    - rvm: 2.1.5
    - rvm: 2.2.0
    - rvm: ruby-head
      
services:
  - postgresql

addons:
  postgresql: "9.3"

script: FIG_RAKE=off RACK_ENV=test bundle exec rake spec
