language: ruby
cache: bundler
sudo: false

before_script: &before_script
  - psql -c 'create database travis_ci_test;' -U postgres
  - mkdir -p tmp
  - RACK_ENV=test bundle exec rake configure:travis db:setup

matrix:
  fast_finish: true
  allow_failures:
  include:
    - rvm: 2.3.0
      env:
        - SPECFOLDER=spec/controllers
        - SPECFOLDER=spec/lib
        - SPECFOLDER=spec/mailers
        - SPECFOLDER=spec/middleware
        - SPECFOLDER=spec/models
        - SPECFOLDER=spec/requests
        - SPECFOLDER=spec/serializers
        - SPECFOLDER=spec/workers

services:
  - postgresql

addons:
  postgresql: "9.4"

script: "RACK_ENV=test bundle exec rspec $SPECFOLDER"
