language: ruby

cache: bundler

jdk: 
  - openjdk7

rvm:
  - 2.1.1
  - 2.1.2
  - jruby-19mode
  - jruby-head

services:
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - rename 's/\.yml.hudson$/\.yml/' config/*.yml.hudson  
  - RACK_ENV=test bundle exec rake db:create db:migrate

script: RACK_EVN=test bundle exec rake spec
