postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=panoptes"
    - "POSTGRES_PASSWORD=panoptes"
  ports:
    - "5432:5432"

zookeeper:
  image: zooniverse/zookeeper
  command: /usr/share/zookeeper/bin/zkServer.sh start-foreground -c localhost:2888:3888 -i 1
  # ports:
  #   - "2181:2181"

redis:
  image: redis
  command: redis-server --appendonly yes
  # ports:
  #   - "6379:6379"

kafka:
  image: zooniverse/kafka
  links:
    - zookeeper:zk
  hostname: kafka
  command: -i 1 -H kafka -p 9092 -z zk:2181

cellect:
  image: zooniverse/cellect-panoptes
  ports:
    - "4000:80"
  environment:
    #cellect registers a hostname but no port, so we need prod port 80
    - "RACK_ENV=production"
    - "DEBUG_CELLECT_START=true"
    - "DATABASE_URL=postgresql://panoptes:panoptes@pg:5432/panoptes_development?pool=16"
    - "ZK_URL=zk:2181"
    - "PUMA_MAX_THREADS=16"
  links:
    - postgres:pg
    - zookeeper:zk

panoptes:
  dockerfile: Dockerfile.dev
  build: ./
  volumes:
    - ./:/rails_app
  ports:
    - "3000:3000"
  environment:
    - "RAILS_ENV=development"
    - "CELLECT_ON=true"
    - "CELLECT_MIN_POOL_SIZE=100"
    - "ZK_URL=zk:2181"
  links:
    - postgres:pg
    - redis
    - zookeeper:zk
    - kafka
