postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=panoptes"
    - "POSTGRES_PASSWORD=panoptes"
  ports:
    - "5432:5432"

zookeeper:
  image: zooniverse/zookeeper
  command: /usr/share/zookeeper/bin/zkServer.sh start-foreground -c localhost:2888:3888 -i 1

redis:
  image: redis
  command: redis-server --appendonly yes

kafka:
  image: zooniverse/kafka
  links:
    - zookeeper:zk
  hostname: kafka
  command: -i 1 -H kafka -p 9092 -z zk:2181

cellect:
  image: zooniverse/cellect-panoptes
  #may have to update the PG env vars since we use a diff
  # postgres image now, https://github.com/zooniverse/cellect_panoptes/blob/master/cellect_env.rb#L49
  links:
    - postgres
    - zookeeper:zk

panoptes:
  dockerfile: Dockerfile.dev
  build: ./
  volumes:
    - ./:/rails_app
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: development
  links:
    - postgres:pg #should it be pg? https://github.com/zooniverse/cellect_panoptes/blob/master/cellect_env.rb
    - zookeeper:zk
    - kafka
    - redis
    - cellect
